language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '9.6' # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "deployment-exercise-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)

before_deploy:
  - npm run build-client # make the bundle
  - rm -rf node_modules # omit from the tarball, since we skip cleanup
deploy:
  skip_cleanup: true # prevents travis from deleting the buil
  provider: heroku
  app: quixotic-legacy # see README
  api_key:
    secure: hchzVqoKzU6QtOiwpfOkG1cKRJx38dsZAnHgprYRlxzxGpZMzPfEoZpujImT+SKifMkhJajACjbpMzxrXpTAsdHInYiTkO+SMfFLV6jcLVyT7ZErdi24Tws5TxuZQEAM5CnRLUzV7Tr09DQlDN6aneT2VgOwAH87zmcumLlMzHvBxg6oQPjrXWym63gTtFMs3JAAEtrMsYqd+XfMy0g81hPHoGNrbAG0z1xcaTq9HI3A5x0EaEfpw8srh5RZ+TmR46saMQjD38ytNAo0KCNEdG43Kw43m5HGI9JaknvsF9HiM+W5DKfmn6VrDc/BYQW2qtIBHoEaBXR6/VRXWoBMWqvOG9k4uzOG1Cjq4GcZd/EQ4JCsC9VYVAoJC3urKrWdrezRzWShjA0YoskbGKIHpzVynbaHGHikq+JfBWr7Amqwlw1ZV5hNAY7jBNgv5xZLlkEyzFRA/qe879CNJhusshV9KbI2CRLhJF3T2ozp4UkLSvcrXyogiCEBZHyO0gHlowejStjnW05G5rBBVUQoQDky4ghOhpuCRvRCCl/4K37Fn4TY8t/SUJJLZdZPATjSxXq1WC3H2Rosh/ofwmrjrHmVRrKW+iEz/uBb6FECfrkdfErUhVfRLzC3Bz/2fJwlrDov3FjDESLvTAAHtq1uuTJpo7gH59JOgmxk8LHVQl8=
