language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '9.6' # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "deployment-exercise-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)

before_deploy:
  - npm run build-client # make the bundle
  - rm -rf node_modules # omit from the tarball, since we skip cleanup
deploy:
  skip_cleanup: true # prevents travis from deleting the buil
  provider: heroku
  app: quixotic-legacy # see README
  api_key:
    secure: pYdMoeYj1DM7RjBd/cI2wACChxE7PqjJSfODAjDP38zyWraHZg/WIVsuy3l0MaXxfZH8Of61M3Ygj4TxPIQxoSQp9k/WGTJph8eK6fxRcFqVjjCo7BQiMJnFQYPHkOXKmA435u9GODLYfDU1tz7U61LZ32qsFLWdKMo/ulI6gUzzeVOTfaPffH2Sr2uHzsP3QCbrZJlZoiWWkMzy6ifRGIdvyDdZBPV4jP2p6OgTYQuYxONBIYR3tDm2C20EHj9Zs6irjF4kGUmwl81fYEXoreU+hjET/6YFhk0y9eQ0TDyV4Zcp/Ewz6XHaDayVTLoOMj+zOwgf9LG+pOISCAwrIkm7H8O3ASGnwyiss1tdKZ5o24VKu2qhRpXkw1I9s8M/NcVQwHufV0/Pfy9cEoXBNCjTlIcDE+2Md/89DafAxQKoq0bNUJSmGfMd3DDD97Fl0Jp5A/JB0wP++37Swnaz4ZFQ87smLFa84i/5JDoOg2xeckGUHaOgoOr8Cs7ITUFxZ7bivyjgu+kq3NyF6UlXy+so53C8QbvCE//2MQYCF5rWK2QL5htMV1nZi1kuC75uF43qT84NY+AefVLmQzzyYiybqDbBkKOH7j27ECvmX/MC3NISyF46lyugLQcnRbw/LQX7qY/Pzm6pS2pY5/+1xvtBXYyhyjO11bjQGYYXF7o=
